name: "Dependency Bot"
on:
  repository_dispatch:
    types: [dependency_update]

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Fetch the labels from the event payload
      - name: Check for update label
        id: label-check
        run: |
          # List of supported labels
          SUPPORTED_LABELS=("alpha" "beta" "latest")

          # Extract the labels from the event payload
          LABELS=$(jq -r '.client_payload.labels[]' <<< '${{ github.event.client_payload }}')

          # Default to "none" if no matching label is found
          MATCHED_LABEL="none"

          # Check if one of the supported labels is present
          for label in $LABELS; do
            for supported_label in "${SUPPORTED_LABELS[@]}"; do
              if [[ "$label" == "$supported_label" ]]; then
                MATCHED_LABEL=$label
                break 2
              fi
            done
          done

          echo "Matched Label: $MATCHED_LABEL"

          # Output the matched label
          echo "::set-output name=matched_label::$MATCHED_LABEL"

      # Conditionally run the dependency update based on the label
      - name: Update dependencies if label matches
        if: steps.label-check.outputs.matched_label != 'none'
        run: |
          case "${{ steps.label-check.outputs.matched_label }}" in
            alpha)
              yarn workspace lit upgrade package-name@alpha
              ;;
            beta)
              yarn workspace lit upgrade package-name@beta
              ;;
            latest)
              yarn workspace lit upgrade package-name@latest
              ;;
            *)
              echo "No matching label found for upgrade."
              ;;
          esac
