name: "Dependency Bot"
on:
  repository_dispatch:
    types: [dependency_update]
  push:
    branches:
      - ci/auto-pub
      - main
      - master

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Fetch the labels from the event payload
      - name: Check for update label
        id: label-check
        run: |
          # List of supported labels
          SUPPORTED_LABELS=("alpha" "beta" "latest")

          # Extract the labels from the event payload
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            LABELS=$(jq -r '.pull_request.labels[].name' <<< '${{ toJson(github.event) }}')
          else
            LABELS=$(jq -r '.client_payload.labels[]' <<< '${{ toJson(github.event.client_payload) }}' 2>/dev/null || echo "")
          fi

          # Default to "none" if no matching label is found
          MATCHED_LABEL="none"

          # Check if one of the supported labels is present
          for label in $LABELS; do
            for supported_label in "${SUPPORTED_LABELS[@]}"; do
              if [[ "$label" == "$supported_label" ]]; then
                MATCHED_LABEL=$label
                break 2
              fi
            done
          done

          echo "Matched Label: $MATCHED_LABEL"

          # Output the matched label
          echo "matched_label=$MATCHED_LABEL" >> $GITHUB_OUTPUT

      # Conditionally run the dependency update based on the label
      - name: Update dependencies if label matches
        if: steps.label-check.outputs.matched_label != 'none'
        run: |
          case "${{ steps.label-check.outputs.matched_label }}" in
            alpha)
              yarn workspace lit-client-setup upgrade @lit-protocol/lit-node-client@alpha
              ;;
            beta)
              yarn workspace lit-client-setup upgrade @lit-protocol/lit-node-client@beta
              ;;
            latest)
              yarn workspace lit-client-setup upgrade @lit-protocol/lit-node-client@latest
              ;;
            *)
              echo "No matching label found for upgrade."
              ;;
          esac
